language: java
jdk:
  - oraclejdk13

install: skip

script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - matheusv.silva@outlook.com
on_success: always
on_failure: always